### ISSUE TITLE
Need final assets

### ISSUE THREAD

**Issue by clayreimann** [cmi-girls-who-code/orpheum-game#10]
We need confirmation of a theme so we can get graphics from the designer.

**Comment by yicyao** [comment]
Theme is ok. 
For ramp game: it is still loosely based on Frozen. We will need an igloo pattern for the ramp, a snowy background, an icy ground, and a snowball. 
For the lever game: We need a castle, a pattern for the lever and the weights, and a giant rock.
We probably need some more graphics as the game progresses.
