### ISSUE TITLE
Ramp can flip

### ISSUE THREAD

**Issue by hadleyshapland** [cmi-girls-who-code/orpheum-game#27]
<img width="766" alt="screen shot 2016-10-17 at 5 49 44 pm" src="https://cloud.githubusercontent.com/assets/21322324/19458509/244e40fc-9492-11e6-85fd-6196db47e4d7.png">

If you expand the ball outside of the screen, it will result in the ramp flipping over and not returning when reset button is clicked.... Should be solved with an anchor point or by giving the ball a max size. Just something to note.

**Comment by anna-troutt** [comment]
Was fixed when issue 5 was fixed
