### ISSUE TITLE
The ramp should never extend under the monster

### ISSUE THREAD

**Issue by clayreimann** [cmi-girls-who-code/orpheum-game#5]
Having the ramp under the monster makes the physics wonky.

**Comment by yicyao** [comment]
Ramp is not set at the right position (left bottom corner should be 0,0) - sometimes when snowball hits, ramp bounces?

**Comment by anna-troutt** [comment]
make isDynamic = false

**Comment by anna-troutt** [comment]
<img width="584" alt="screen shot 2016-10-24 at 5 52 25 pm" src="https://cloud.githubusercontent.com/assets/22756571/19666868/b740cd82-9a12-11e6-9a36-ae05ab0b35d9.png">

**Comment by anna-troutt** [comment]
Ramp boundaries were apparently fixed - problem stopped when dynamics were set...
