### ISSUE TITLE
The game should appear the same on all devices of all sizes

### ISSUE THREAD

**Issue by clayreimann** [cmi-girls-who-code/orpheum-game#7]
This could likely be solved one of two ways:
- either by calculating positions relative to the edge of the device rather than fixed positions
- or by applying some scaling factor for larger/smaller devices

**Comment by anna-troutt** [comment]
<img width="654" alt="screen shot 2016-11-28 at 5 55 11 pm" src="https://cloud.githubusercontent.com/assets/22756571/20691077/17246b2c-b594-11e6-95d1-0a61c76772dd.png">
